<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Property;
use App\Services\ExportService;
use App\Services\ReportBuilder;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class ReportController extends Controller
{
    public function __construct(
        private readonly ReportBuilder $reports,
        private readonly ExportService $exports,
    ) {}

    /** The on-screen report table: projected rows plus the company-total row. */
    public function index(Request $request): JsonResponse
    {
        $this->authorize('viewAny', Property::class);

        $columns = $this->columns($request);
        $properties = $this->properties($request);
        $rows = $this->reports->project($this->reports->rows($properties), $columns);

        return response()->json([
            'columns' => $columns,
            'availableColumns' => ReportBuilder::ALL_COLUMNS,
            'rows' => $rows,
            'totals' => $this->reports->totalsRow($rows, $columns),
            'propertyCount' => $properties->count(),
            'unitCount' => $properties->sum(fn (Property $p) => $p->totalUnits()),
            'filterActive' => $this->filterActive($request),
        ]);
    }

    /**
     * Download the same report as a file. Format is csv, xlsx or pdf; the body
     * is returned as a binary response the iOS app hands to the share sheet.
     */
    public function export(Request $request, string $format): Response
    {
        $this->authorize('export', Property::class);

        abort_unless(in_array($format, ['csv', 'xlsx', 'pdf'], true), 404);

        $columns = $this->columns($request);
        $properties = $this->properties($request);
        $rows = $this->reports->project($this->reports->rows($properties), $columns);

        $filterActive = $this->filterActive($request);
        $filename = 'london-'.($filterActive ? 'filtered' : 'portfolio').'-'.now()->format('Y-m-d');

        $summary = [
            'Properties' => $properties->count(),
            'Total accommodation units' => $properties->sum(fn (Property $p) => $p->totalUnits()),
            'Total elevators' => $properties->sum(fn (Property $p) => $p->elevators->count()),
            'Verified properties' => $properties->where('verification_status', Property::STATUS_VERIFIED)->count(),
            'Scope' => $filterActive ? 'Filtered selection' : 'Entire company',
            'Generated' => now()->format('Y-m-d H:i'),
            'Generated by' => $request->user()->name,
        ];

        [$body, $mime, $extension] = match ($format) {
            'csv' => [$this->exports->csv($rows, $columns), 'text/csv', 'csv'],
            'xlsx' => [
                $this->exports->xlsx($rows, $columns, $summary),
                'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'xlsx',
            ],
            'pdf' => [$this->exports->pdf($rows, $columns, $summary), 'application/pdf', 'pdf'],
        };

        return response($body, 200, [
            'Content-Type' => $mime,
            'Content-Disposition' => 'attachment; filename="'.$filename.'.'.$extension.'"',
            'Content-Length' => (string) strlen($body),
            'X-Filename' => $filename.'.'.$extension,
        ]);
    }

    /* ------------------------------------------------------------------ */

    private function properties(Request $request)
    {
        $query = Property::query()
            ->with(['accommodation', 'elevators', 'staircases', 'documents', 'changeLogs', 'changeFlags', 'fieldValues.fieldDefinition'])
            ->visibleTo($request->user());

        // `scope=all` exports everything the user may see, ignoring the current
        // filter — the "Export Entire Portfolio" button.
        if ($request->query('scope') !== 'all') {
            $query->filtered([
                'borough' => $request->query('borough'),
                'council' => $request->query('council'),
                'region' => $request->query('region'),
                'property_type' => $request->query('propertyType'),
                'verification' => $request->query('verification'),
                'q' => $request->query('q'),
            ]);
        }

        return $query->orderBy('site_name')->get();
    }

    private function columns(Request $request): array
    {
        $requested = $request->query('columns');

        if (is_string($requested)) {
            $requested = array_filter(array_map('trim', explode(',', $requested)));
        }

        $columns = array_values(array_intersect(
            is_array($requested) ? $requested : [],
            ReportBuilder::ALL_COLUMNS,
        ));

        return $columns ?: ReportBuilder::DEFAULT_COLUMNS;
    }

    private function filterActive(Request $request): bool
    {
        if ($request->query('scope') === 'all') {
            return false;
        }

        return collect(['borough', 'council', 'region', 'propertyType', 'verification', 'q'])
            ->contains(fn ($key) => filled($request->query($key)));
    }
}
